# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_keys import g_key


# Access maps with unique API key
gmaps.configure(api_key=g_key)

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [2]:
weather_data = pd.read_csv('..\weatherpy-outfile.csv')

weather_data.head(40)

,city,lat,lng,max_temp,humidity,cloudiness,wind_speed,country,date
0,Mataura,-46.19,168.86,44.01,89,96,1.99,NZ,1603211273
1,Alyangula,-13.85,136.42,78.80,88,17,2.24,AU,1603210769
2,Stromness,58.97,-3.30,50.00,93,90,21.92,GB,1603211278
3,Yellowknife,62.46,-114.35,24.80,85,75,3.36,CA,1603210854
4,Chivacoa,10.16,-68.89,87.80,43,100,10.29,VE,1603211278
5,Port Alfred,-33.59,26.89,63.57,64,82,19.75,ZA,1603211278
6,Airai,-8.93,125.41,61.47,80,100,1.86,TL,1603211278
7,Cape Town,-33.93,18.42,64.00,51,3,17.22,ZA,1603211278
8,Jamestown,42.10,-79.24,48.99,100,90,6.93,US,1603211088
9,Yaan,7.38,8.57,85.46,71,50,2.80,NG,1603211195
10,Fort Myers Beach,26.45,-81.95,82.00,83,20,8.05,US,1603210717
11,Ushuaia,-54.80,-68.30,44.60,56,40,23.04,AR,1603211003
12,Pevek,69.70,170.31,31.17,94,91,20.85,RU,1603210689
13,Clifton,40.86,-74.16,69.01,88,90,5.82,US,1603211227
14,Buala,-8.14,159.59,80.13,78,83,2.51,SB,1603211278
15,Porbandar,21.64,69.61,84.40,77,6,10.60,IN,1603211279
16,Clemson,34.68,-82.84,73.00,60,1,3.27,US,1603211279
17,Khatanga,71.97,102.50,7.36,96,83,8.46,RU,1603211048
18,Saskylakh,71.92,114.08,21.22,97,86,5.77,RU,1603211279
19,Ābdānān,32.99,47.42,61.30,31,0,2.37,IR,1603211279
20,San Patricio,28.02,-97.52,86.00,66,75,8.05,US,1603210702
21,Albany,42.60,-73.97,63.00,76,100,2.98,US,1603211020
22,Hithadhoo,-0.60,73.08,83.07,77,72,11.68,MV,1603210889
23,Portland,45.52,-122.68,54.00,81,75,2.04,US,1603210517
24,Xuanwu,32.07,118.81,66.99,69,100,4.41,CN,1603211279
25,Vaini,-21.20,-175.20,69.80,77,20,11.41,TO,1603210720
26,Bambous Virieux,-20.34,57.76,75.99,73,40,12.75,MU,1603211279
27,Geraldton,-28.77,114.60,64.40,77,90,16.11,AU,1603211260
28,Lagoa,39.05,-27.98,63.54,67,14,26.26,PT,1603211279
29,Ribeira Grande,38.52,-28.70,64.40,68,40,5.82,PT,1603210745
30,East London,-33.02,27.91,62.60,67,45,25.28,ZA,1603210836
31,Thinadhoo,0.53,72.93,83.37,77,33,12.15,MV,1603211280
32,Korla,41.76,86.15,50.00,68,0,5.01,CN,1603211280
33,Ushumun,52.78,126.53,38.34,90,100,10.31,RU,1603211280
34,Hong Kong,22.29,114.16,75.00,66,5,3.00,HK,1603210481
35,Charters Towers,-20.10,146.27,67.93,85,0,7.49,AU,1603210886
36,Gizo Government Station,-8.10,156.84,82.81,74,68,6.60,SB,1603211280
37,Rikitea,-23.12,-134.97,73.27,78,4,12.88,PF,1603211266
38,Butaritari,3.07,172.79,81.81,74,100,9.24,KI,1603211281
39,Banganapalle,15.32,78.23,76.71,83,100,3.40,IN,1603211281

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [17]:
locations = weather_data[["lat", "lng"]].astype(float)

# HINT: be sure to handle NaN values
#census_data_complete = census_data_complete.dropna()

humidity_ls = weather_data["humidity"].astype(float)

In [15]:
figure_layout = {
    'width': '1200px',
    'height': '800px',
    'border': '1px solid black',
    'padding': '1px',
    'margin': '0 auto 0 auto'
}
fig = gmaps.figure(layout=figure_layout)

#create heat layer
heat_layer = gmaps.heatmap_layer(locations, weights=humidity_ls, 
                                 dissipating=False, max_intensity=100,
                                 point_radius = 1)

fig.add_layer(heat_layer)

#print
fig

Figure(layout=FigureLayout(border='1px solid black', height='800px', margin='0 auto 0 auto', padding='1px', wi…

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [6]:
#create ideal weather list  between 60-80 degrees with less 10% cloudiness and windspeed less than 2 mph
ideal_weather_data = weather_data.loc[(weather_data["max_temp"] < 80) &
                                     (weather_data["max_temp"] > 60) & 
                                      (weather_data["cloudiness"] < 10) &
                                        (weather_data["wind_speed"] < 2)]
                                     
ideal_weather_data.head(25)

,city,lat,lng,max_temp,humidity,cloudiness,wind_speed,country,date
260,Lake Shasta,40.68,-122.37,79.00,28,0,1.99,US,1603211606
367,Santa Catarina de Tepehuanes,25.35,-105.73,76.05,29,0,0.85,MX,1603211734
484,Sciacca,37.51,13.09,62.01,58,0,1.99,IT,1603211925
544,Jalalabad,34.43,70.45,74.21,25,0,1.81,AF,1603211992

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [7]:
#create hotel df & set parameter for google
hotel_df = []
params = {
    "radius": 5000,
    "types": "hotel",
    "keyword":"hotel",
    "key": g_key
}

# Use the lat/lng to identify cities
for index, row in ideal_weather_data.iterrows():
    # get lat, lng from df
    lat = row["lat"]
    lng = row["lng"]

    # change location each iteration while leaving original params in place
    params["location"] = f"{lat},{lng}"

    # Use the search terms and lat/lng
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # make request and print url
    hotel_data = requests.get(base_url, params=params).json()
    
    #checking for errors
    try:
        print(hotel_data["results"][0]["name"])
        hotel_df.append(hotel_data["results"][0]["name"])
    except (KeyError, IndexError):
        hotel_df.append("No hotel found")
    
print(hotel_df)    
    
ideal_weather_data["Hotel Name"] = hotel_df    

ideal_weather_data.head(6)

Hotel Palma
this is the jsonx
Domus Maris Boutique Hotel a Sciacca
this is the jsonx
تالار ستاره شرق
this is the jsonx
['No hotel found', 'Hotel Palma', 'Domus Maris Boutique Hotel a Sciacca', 'تالار ستاره شرق']

C:\Users\Buddy\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:48: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,city,lat,lng,max_temp,humidity,cloudiness,wind_speed,country,date,Hotel Name
260,Lake Shasta,40.68,-122.37,79.00,28,0,1.99,US,1603211606,No hotel found
367,Santa Catarina de Tepehuanes,25.35,-105.73,76.05,29,0,0.85,MX,1603211734,Hotel Palma
484,Sciacca,37.51,13.09,62.01,58,0,1.99,IT,1603211925,Domus Maris Boutique Hotel a Sciacca
544,Jalalabad,34.43,70.45,74.21,25,0,1.81,AF,1603211992,تالار ستاره شرق

In [12]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>city</dt><dd>{city}</dd>
<dt>country</dt><dd>{country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in ideal_weather_data.iterrows()]
i_locations = ideal_weather_data[["lat", "lng"]]

In [16]:
# Add marker layer ontop of heat map
figure_layout = {
    'width': '1200px',
    'height': '800px',
    'border': '1px solid black',
    'padding': '1px',
    'margin': '0 auto 0 auto'
}

fig = gmaps.figure(layout=figure_layout)

#recreate heat map from above
heat_layer = gmaps.heatmap_layer(locations, weights=humidity_ls, 
                                 dissipating=False, max_intensity=100,
                                 point_radius = 1)

fig.add_layer(heat_layer)


#create markers for Hotels
markers = gmaps.marker_layer(i_locations,info_box_content = hotel_info)

# Add the layer to the map
fig.add_layer(markers)

# Display figure
fig

Figure(layout=FigureLayout(border='1px solid black', height='800px', margin='0 auto 0 auto', padding='1px', wi…