# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_keys import g_key


# Access maps with unique API key
gmaps.configure(api_key=g_key)

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [2]:
weather_data = pd.read_csv('..\weatherpy-outfile.csv')

weather_data.head(40)

,city,lat,lng,max_temp,humidity,cloudiness,wind_speed,country,date
0,Sunnyside,46.32,-120.01,62.01,62,1,6.17,US,1603161277
1,Bredasdorp,-34.53,20.04,57.20,71,51,12.75,ZA,1603161524
2,George Town,5.41,100.34,84.20,79,20,1.12,MY,1603161524
3,College,64.86,-147.80,21.99,85,90,1.57,US,1603161524
4,Buribay,51.96,58.16,47.16,50,86,7.81,RU,1603161524
5,Constanța,44.18,28.65,46.40,70,70,6.93,RO,1603161524
6,Vestmannaeyjar,63.44,-20.27,39.38,77,72,3.38,IS,1603161524
7,Conceição do Araguaia,-8.26,-49.26,80.82,47,100,0.85,BR,1603161524
8,Marsh Harbour,26.54,-77.06,81.30,76,100,19.33,BS,1603161524
9,Rikitea,-23.12,-134.97,74.30,77,0,10.58,PF,1603161524
10,Saint Paul Harbor,57.79,-152.41,46.40,49,1,9.17,US,1603161519
11,Viedma,-40.81,-63.00,46.00,61,0,6.11,AR,1603161525
12,Puerto Ayora,-0.74,-90.35,69.01,92,91,7.00,EC,1603161449
13,Pyapon,16.28,95.68,77.14,94,100,14.03,MM,1603161525
14,Whitehorse,60.72,-135.05,24.80,68,90,0.60,CA,1603161525
15,Qaanaaq,77.48,-69.36,28.58,88,68,6.51,GL,1603161525
16,Clyde River,70.47,-68.59,32.00,91,90,10.29,CA,1603161525
17,Abhā,18.22,42.51,53.60,27,0,4.70,SA,1603161273
18,Shache,38.42,77.24,55.92,33,0,2.15,CN,1603161525
19,Hithadhoo,-0.60,73.08,82.60,78,87,13.58,MV,1603161525
20,Esperance,-33.87,121.90,64.40,93,90,10.29,AU,1603161525
21,Hearst,49.68,-83.67,25.70,97,28,4.07,CA,1603161393
22,Nkhata Bay,-11.61,34.29,74.53,64,0,2.86,MW,1603161525
23,Tulsīpur,28.13,82.30,75.00,98,0,1.99,NP,1603161525
24,Cape Town,-33.93,18.42,59.00,87,75,6.93,ZA,1603161525
25,Jamestown,42.10,-79.24,54.00,93,90,10.29,US,1603161525
26,Ushuaia,-54.80,-68.30,35.60,92,75,31.09,AR,1603161347
27,Torbay,47.67,-52.73,48.99,87,20,10.29,CA,1603161526
28,Port Elizabeth,-33.92,25.57,59.00,82,73,23.04,ZA,1603161526
29,Kapaa,22.08,-159.32,84.99,66,40,10.29,US,1603161526
30,Arraial do Cabo,-22.97,-42.03,73.40,78,20,18.34,BR,1603161526
31,Bălţi,47.76,27.93,41.00,86,13,2.24,MD,1603161526
32,Busselton,-33.65,115.33,73.99,37,1,7.63,AU,1603161526
33,Bilma,18.69,12.92,76.66,18,0,3.06,NE,1603161526
34,Mataura,-46.19,168.86,53.01,66,88,18.01,NZ,1603161526
35,Punta Arenas,-53.15,-70.92,39.20,80,20,20.80,CL,1603161526
36,La Libertad,-2.23,-80.90,70.05,86,96,13.67,EC,1603161526
37,Mehamn,71.04,27.85,37.33,80,100,14.72,NO,1603161394
38,Lüderitz,-26.65,15.16,57.36,69,0,22.15,NaN,1603161526
39,Belyy Yar,53.60,91.39,33.80,74,100,11.18,RU,1603161527

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [3]:
locations = weather_data[["lat", "lng"]].astype(float)

# HINT: be sure to handle NaN values
#census_data_complete = census_data_complete.dropna()

humidity_ls = weather_data["humidity"].astype(float)
print(humidity_ls)

0      62.0
1      71.0
2      79.0
3      85.0
4      50.0
       ...
98     87.0
99     95.0
100    93.0
101    94.0
102    85.0
Name: humidity, Length: 103, dtype: float64

In [43]:
figure_layout = {
    'width': '1200px',
    'height': '800px',
    'border': '1px solid black',
    'padding': '1px',
    'margin': '0 auto 0 auto'
}
fig = gmaps.figure(layout=figure_layout)
#fig


#fig = gmaps.figure()

heat_layer = gmaps.heatmap_layer(locations, weights=humidity_ls, 
                                 dissipating=False, max_intensity=100,
                                 point_radius = 1)

fig.add_layer(heat_layer)

fig

#markers = gmaps.marker_layer(locations)
# Add the layer to the map
#fig.add_layer(markers)
#fig

Figure(layout=FigureLayout(border='1px solid black', height='800px', margin='0 auto 0 auto', padding='1px', wi…

In [9]:
# Customize the size of the figure
#figure_layout = {
#    'width': '400px',
#    'height': '300px',
#    'border': '1px solid black',
#    'padding': '1px',
#    'margin': '0 auto 0 auto'
#}
#fig = gmaps.figure(layout=figure_layout)

In [18]:
#

In [17]:
#

In [20]:
# Assign the marker layer to a variable
markers = gmaps.marker_layer(locations)
# Add the layer to the map
fig.add_layer(markers)
fig

Figure(layout=FigureLayout(border='1px solid black', height='800px', margin='0 auto 0 auto', padding='1px', wi…

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [44]:
ideal_weather_data = weather_data.loc[(weather_data["max_temp"] < 80) &
                                     (weather_data["max_temp"] > 60) & 
                                      (weather_data["cloudiness"] > 0) &
                                        (weather_data["wind_speed"] < 5)]
                                     
                                     
                                     
                                                                 
                                    #weather_data["wind_speed"] <10]
                                     # < 10|weather_data["cloudiness"] == 70 
            
            #|weather_data["max_temp"] < 80|
                                                                       
                                    # ]

ideal_weather_data.head(25)

,city,lat,lng,max_temp,humidity,cloudiness,wind_speed,country,date
44,New Norfolk,-42.78,147.06,66.99,61,76,1.99,AU,1603161588
51,Nobres,-14.72,-56.33,76.35,74,99,2.73,BR,1603161588
55,Nortelândia,-14.45,-56.80,73.44,82,97,3.44,BR,1603161588
62,Jacareacanga,-6.22,-57.75,77.07,75,100,2.30,BR,1603161589
73,Tomatlán,19.93,-105.25,77.20,92,28,1.10,MX,1603161589
95,Pineville,31.32,-92.43,73.40,78,1,3.36,US,1603161372

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [54]:
hotel_df = []
params = {
    "radius": 5000,
    "types": "hotel",
    "keyword":"hotel",
    "key": g_key
}

# Use the lat/lng we recovered to identify cities
for index, row in ideal_weather_data.iterrows():
    # get lat, lng from df
    lat = row["lat"]
    lng = row["lng"]

    # change location each iteration while leaving original params in place
    params["location"] = f"{lat},{lng}"

    # Use the search term: "International Airport" and our lat/lng
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # make request and print url
    hotel_data = requests.get(base_url, params=params).json()
    
    try:
        #bl
        #print(hotel_data)
        print(hotel_data["results"][0]["name"])
        hotel_df.append(hotel_data["results"][0]["name"])
        #print(json.dumps(name_address, indent=4, sort_keys=True))
        xx = input("this is the json")
    except (KeyError, IndexError):
        hotel_df.append("No hotel found")
    
print(hotel_df)    
    
# Run a request to endpoint and convert result to json
#geo_data = requests.get(target_url).json()

# Print the json
#print(geo_data)

# Print the json (pretty printed)
#print(json.dumps(geo_data, indent=4, sort_keys=True))
    
    
    
    
ideal_weather_data["Hotel Name"] = hotel_df    
    
    
    
    
#     print the name_address url, avoid doing for public github repos in order to avoid exposing key
#     print(name_address.url)

    # convert to json
    #name_address = name_address.json()
  

    # Since some data may be missing we incorporate a try-except to skip any that are missing a data point.
    #try:
    #    cities_pd.loc[index, "Airport Name"] = name_address["results"][0]["name"]
    #    cities_pd.loc[index, "Airport Address"] = name_address["results"][0]["vicinity"]
    #    cities_pd.loc[index, "Airport Rating"] = name_address["results"][0]["rating"]
    #except (KeyError, IndexError):
    #    print("Missing field/result... skipping.")


#print(json.dumps(response_json, indent=4, sort_keys=True))
ideal_weather_data.head(6)

Hotel Hebrom
this is the jsonx
Hotel Karysmã
this is the jsonx
HOTEL VIANA
this is the jsonx
Hotel Hacienda Vieja
this is the jsonx
The Hotel Bentley of Alexandria
this is the jsonx
['No hotel found', 'Hotel Hebrom', 'Hotel Karysmã', 'HOTEL VIANA', 'Hotel Hacienda Vieja', 'The Hotel Bentley of Alexandria']

C:\Users\Buddy\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:48: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,city,lat,lng,max_temp,humidity,cloudiness,wind_speed,country,date,Hotel Name
44,New Norfolk,-42.78,147.06,66.99,61,76,1.99,AU,1603161588,No hotel found
51,Nobres,-14.72,-56.33,76.35,74,99,2.73,BR,1603161588,Hotel Hebrom
55,Nortelândia,-14.45,-56.80,73.44,82,97,3.44,BR,1603161588,Hotel Karysmã
62,Jacareacanga,-6.22,-57.75,77.07,75,100,2.30,BR,1603161589,HOTEL VIANA
73,Tomatlán,19.93,-105.25,77.20,92,28,1.10,MX,1603161589,Hotel Hacienda Vieja
95,Pineville,31.32,-92.43,73.40,78,1,3.36,US,1603161372,The Hotel Bentley of Alexandria

In [58]:
ideal_weather_data.head(6)

,city,lat,lng,max_temp,humidity,cloudiness,wind_speed,country,date,Hotel Name
44,New Norfolk,-42.78,147.06,66.99,61,76,1.99,AU,1603161588,No hotel found
51,Nobres,-14.72,-56.33,76.35,74,99,2.73,BR,1603161588,Hotel Hebrom
55,Nortelândia,-14.45,-56.80,73.44,82,97,3.44,BR,1603161588,Hotel Karysmã
62,Jacareacanga,-6.22,-57.75,77.07,75,100,2.30,BR,1603161589,HOTEL VIANA
73,Tomatlán,19.93,-105.25,77.20,92,28,1.10,MX,1603161589,Hotel Hacienda Vieja
95,Pineville,31.32,-92.43,73.40,78,1,3.36,US,1603161372,The Hotel Bentley of Alexandria

In [47]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>city</dt><dd>{city}</dd>
<dt>country</dt><dd>{country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in ideal_weather_data.iterrows()]
locations = ideal_weather_data[["lat", "lng"]]

In [25]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]
hotel_df

AttributeError: 'list' object has no attribute 'iterrows'

In [48]:
# Add marker layer ontop of heat map
figure_layout = {
    'width': '1200px',
    'height': '800px',
    'border': '1px solid black',
    'padding': '1px',
    'margin': '0 auto 0 auto'
}
fig = gmaps.figure(layout=figure_layout)







markers = gmaps.marker_layer(locations,info_box_content = hotel_info)
# Add the layer to the map
fig.add_layer(markers)
fig
# Display figure

Figure(layout=FigureLayout(border='1px solid black', height='800px', margin='0 auto 0 auto', padding='1px', wi…