# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [3]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_keys import g_key


# Access maps with unique API key
gmaps.configure(api_key=g_key)

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [10]:
weather_data = pd.read_csv('..\weatherpy-outfile.csv')

weather_data.head(25)

,city,lat,lng,max_temp,humidity,cloudiness,wind_speed,country,date
0,London,51.51,-0.13,52.00,87,90,5.82,GB,1602899780
1,Hoboken,40.74,-74.03,53.60,93,90,6.93,US,1602899951
2,Paris,48.85,2.35,50.00,87,90,4.70,FR,1602899433
3,Lima,-12.04,-77.03,64.40,82,40,13.87,PE,1602899757
4,Cairo,30.06,31.25,68.00,77,40,8.05,EG,1602899803
5,Manaus,-3.10,-60.02,82.40,88,26,1.50,BR,1602899923
6,Ngorongoro,-3.24,35.49,49.44,96,0,5.99,TZ,1602899952
7,Ushuaia,-54.80,-68.30,42.80,92,40,23.04,AR,1602899952
8,Provideniya,64.38,-173.30,39.92,87,1,10.67,RU,1602899476
9,Tiksi,71.69,128.87,25.54,98,100,8.28,RU,1602899552
10,Georgiyevka,43.04,74.71,35.60,46,0,4.47,KZ,1602899952
11,Saskylakh,71.92,114.08,5.92,94,99,3.76,RU,1602899574
12,Mayo,38.89,-76.51,53.60,66,90,8.05,US,1602899952
13,Quito,-0.23,-78.52,57.20,87,20,6.93,EC,1602899845
14,Osasco,-23.53,-46.79,60.01,82,75,11.41,BR,1602899875
15,Trujillo,-8.12,-79.03,63.32,83,77,4.59,PE,1602899952
16,Yellowknife,62.46,-114.35,25.00,85,90,21.92,CA,1602899952
17,Isangel,-19.55,169.27,82.40,74,20,11.41,VU,1602899625
18,Ayan,56.45,138.17,37.15,72,37,4.16,RU,1602899952
19,Giohar,2.78,45.50,78.15,78,100,11.99,SO,1602899952
20,Whitehorse,60.72,-135.05,17.60,44,40,11.41,CA,1602899557
21,Mar del Plata,-38.00,-57.56,57.00,100,90,6.93,AR,1602899697
22,Nelson Bay,-32.72,152.15,84.99,45,47,5.82,AU,1602899647
23,Alice Springs,-23.70,133.88,96.80,22,0,18.34,AU,1602899952

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [11]:
locations = weather_data[["lat", "lng"]].astype(float)

# Convert Poverty Rate to float and store
# HINT: be sure to handle NaN values
#census_data_complete = census_data_complete.dropna()

humidity_ls = weather_data["humidity"].astype(float)

In [14]:
figure_layout = {
    'width': '400px',
    'height': '300px',
    'border': '1px solid black',
    'padding': '1px',
    'margin': '0 auto 0 auto'
}
fig = gmaps.figure(layout=figure_layout)
#fig


#fig = gmaps.figure()

heat_layer = gmaps.heatmap_layer(locations, weights=humidity_ls, 
                                 dissipating=False, max_intensity=100,
                                 point_radius = 1)

fig.add_layer(heat_layer)

fig

Figure(layout=FigureLayout(border='1px solid black', height='300px', margin='0 auto 0 auto', padding='1px', wi…

In [3]:
# Customize the size of the figure
figure_layout = {
    'width': '400px',
    'height': '300px',
    'border': '1px solid black',
    'padding': '1px',
    'margin': '0 auto 0 auto'
}
fig = gmaps.figure(layout=figure_layout)

In [4]:
# Create a list containing coordinates
coordinates = [
    (40.71, -74.00),
    (30.26, -97.74),
    (46.87, -96.78),
    (47.60, -122.33),
    (32.71, -117.16)
]

In [7]:
# Customize the size of the figure
figure_layout = {
    'width': '400px',
    'height': '300px',
    'border': '1px solid black',
    'padding': '1px',
    'margin': '0 auto 0 auto'
}
fig = gmaps.figure(layout=figure_layout)
fig

Figure(layout=FigureLayout(border='1px solid black', height='300px', margin='0 auto 0 auto', padding='1px', wi…

In [6]:
# Assign the marker layer to a variable
markers = gmaps.marker_layer(coordinates)
# Add the layer to the map
fig.add_layer(markers)
fig

Figure(layout=FigureLayout(border='1px solid black', height='300px', margin='0 auto 0 auto', padding='1px', wi…

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [32]:
ideal_weather_data = weather_data.loc[(weather_data["max_temp"] < 80) &
                                     (weather_data["max_temp"] > 60) & 
                                      (weather_data["cloudiness"] > 0) &
                                        (weather_data["wind_speed"] < 5)]
                                     
                                     
                                     
                                                                 
                                    #weather_data["wind_speed"] <10]
                                     # < 10|weather_data["cloudiness"] == 70 
            
            #|weather_data["max_temp"] < 80|
                                                                       
                                    # ]

ideal_weather_data.head(25)

,city,lat,lng,max_temp,humidity,cloudiness,wind_speed,country,date
15,Trujillo,-8.12,-79.03,63.32,83,77,4.59,PE,1602899952

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [ ]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [ ]:
# Add marker layer ontop of heat map


# Display figure