# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_keys import g_key


# Access maps with unique API key
gmaps.configure(api_key=g_key)

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [3]:
weather_data = pd.read_csv('..\weatherpy-outfile.csv')

weather_data.head(25)

,city,lat,lng,max_temp,humidity,cloudiness,wind_speed,country,date
0,Port Townsend,48.12,-122.76,55.99,66,75,8.05,US,1603151836
1,Hithadhoo,-0.60,73.08,82.69,77,94,13.11,MV,1603151837
2,Bambous Virieux,-20.34,57.76,73.40,78,40,9.17,MU,1603151837
3,Madimba,-10.40,40.33,69.80,88,20,2.44,TZ,1603151837
4,Alcântara,-2.41,-44.41,80.60,83,50,12.75,BR,1603151837
5,Port Elizabeth,-33.92,25.57,60.80,82,20,17.22,ZA,1603151837
6,Bluff,-46.60,168.33,50.00,86,88,8.99,NZ,1603151687
7,Punta Arenas,-53.15,-70.92,41.00,75,20,33.33,CL,1603151687
8,North Bend,43.41,-124.22,61.00,77,1,16.11,US,1603151837
9,Khatanga,71.97,102.50,10.45,96,40,1.36,RU,1603151687
10,Saint-Philippe,-21.36,55.77,70.00,64,36,6.93,RE,1603151687
11,Rikitea,-23.12,-134.97,74.43,77,0,11.95,PF,1603151837
12,Cabedelo,-6.98,-34.83,75.20,83,20,5.82,BR,1603151837
13,Juneau,58.30,-134.42,41.00,80,75,2.68,US,1603151640
14,Amroha,28.92,78.47,64.81,31,0,3.76,IN,1603151837
15,Nara,34.69,135.80,55.40,100,75,1.12,JP,1603151837
16,San Cristobal,7.77,-72.22,86.00,51,40,10.29,VE,1603151837
17,Puerto Ayora,-0.74,-90.35,70.00,90,98,4.00,EC,1603151687
18,São José da Coroa Grande,-8.90,-35.15,76.05,78,64,10.42,BR,1603151837
19,Ushuaia,-54.80,-68.30,41.00,80,75,34.45,AR,1603151565
20,Doha,25.29,51.53,82.40,45,0,5.82,QA,1603151838
21,Ribeira Grande,38.52,-28.70,64.17,68,46,27.69,PT,1603151838
22,Damāvand,35.72,52.06,55.40,32,0,4.70,IR,1603151838
23,Hilo,19.73,-155.09,84.20,54,1,13.87,US,1603151687
24,Ponta Delgada,37.73,-25.67,59.00,77,40,11.41,PT,1603151838

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [5]:
locations = weather_data[["lat", "lng"]].astype(float)

# HINT: be sure to handle NaN values
#census_data_complete = census_data_complete.dropna()

humidity_ls = weather_data["humidity"].astype(float)

In [23]:
figure_layout = {
    'width': '1200px',
    'height': '800px',
    'border': '1px solid black',
    'padding': '1px',
    'margin': '0 auto 0 auto'
}
fig = gmaps.figure(layout=figure_layout)
#fig


#fig = gmaps.figure()

heat_layer = gmaps.heatmap_layer(locations, weights=humidity_ls, 
                                 dissipating=False, max_intensity=100,
                                 point_radius = 1)

fig.add_layer(heat_layer)

fig

markers = gmaps.marker_layer(locations)
# Add the layer to the map
fig.add_layer(markers)
fig

Figure(layout=FigureLayout(border='1px solid black', height='800px', margin='0 auto 0 auto', padding='1px', wi…

In [9]:
# Customize the size of the figure
#figure_layout = {
#    'width': '400px',
#    'height': '300px',
#    'border': '1px solid black',
#    'padding': '1px',
#    'margin': '0 auto 0 auto'
#}
#fig = gmaps.figure(layout=figure_layout)

In [18]:
#

In [17]:
#

In [20]:
# Assign the marker layer to a variable
markers = gmaps.marker_layer(locations)
# Add the layer to the map
fig.add_layer(markers)
fig

Figure(layout=FigureLayout(border='1px solid black', height='800px', margin='0 auto 0 auto', padding='1px', wi…

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [24]:
ideal_weather_data = weather_data.loc[(weather_data["max_temp"] < 80) &
                                     (weather_data["max_temp"] > 60) & 
                                      (weather_data["cloudiness"] > 0) &
                                        (weather_data["wind_speed"] < 5)]
                                     
                                     
                                     
                                                                 
                                    #weather_data["wind_speed"] <10]
                                     # < 10|weather_data["cloudiness"] == 70 
            
            #|weather_data["max_temp"] < 80|
                                                                       
                                    # ]

ideal_weather_data.head(25)

,city,lat,lng,max_temp,humidity,cloudiness,wind_speed,country,date
3,Madimba,-10.40,40.33,69.80,88,20,2.44,TZ,1603151837
17,Puerto Ayora,-0.74,-90.35,70.00,90,98,4.00,EC,1603151687
33,Hong Kong,22.29,114.16,73.99,75,10,1.99,HK,1603151406

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [25]:
hotel_df = []
params = {
    "radius": 5000,
    "types": "hotel",
    "keyword":"hotel",
    "key": g_key
}

# Use the lat/lng we recovered to identify cities
for index, row in ideal_weather_data.iterrows():
    # get lat, lng from df
    lat = row["lat"]
    lng = row["lng"]

    # change location each iteration while leaving original params in place
    params["location"] = f"{lat},{lng}"

    # Use the search term: "International Airport" and our lat/lng
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # make request and print url
    hotel_data = requests.get(base_url, params=params).json()
    
    try:
        #print(hotel_data)
        print(hotel_data["results"][0]["name"])
        hotel_df.append(hotel_data["results"][0]["name"])
        #print(json.dumps(name_address, indent=4, sort_keys=True))
        xx = input("this is the json")
    except (KeyError, IndexError):
        print("Missing result... skipping.")
    
print(hotel_df)    
    
# Run a request to endpoint and convert result to json
#geo_data = requests.get(target_url).json()

# Print the json
#print(geo_data)

# Print the json (pretty printed)
#print(json.dumps(geo_data, indent=4, sort_keys=True))
    
    
    
    
    
    
    
    
    
#     print the name_address url, avoid doing for public github repos in order to avoid exposing key
#     print(name_address.url)

    # convert to json
    #name_address = name_address.json()
  

    # Since some data may be missing we incorporate a try-except to skip any that are missing a data point.
    #try:
    #    cities_pd.loc[index, "Airport Name"] = name_address["results"][0]["name"]
    #    cities_pd.loc[index, "Airport Address"] = name_address["results"][0]["vicinity"]
    #    cities_pd.loc[index, "Airport Rating"] = name_address["results"][0]["rating"]
    #except (KeyError, IndexError):
    #    print("Missing field/result... skipping.")


#print(json.dumps(response_json, indent=4, sort_keys=True))

Missing result... skipping.
Finch Bay Galapagos Hotel
this is the jsonx
Royal Plaza Hotel 帝京酒店
this is the jsonx
['Finch Bay Galapagos Hotel', 'Royal Plaza Hotel 帝京酒店']

In [ ]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [ ]:
# Add marker layer ontop of heat map


# Display figure